// Server-side version of demo action registry for pattern matching
// Keep in sync with front-end src/utils/demoActionsRegistry.js

const demoActions = [
  { key: 'users.access.update', methods: ['PUT','PATCH'], urlPatterns: [/^\/api\/users\/.+\/access$/] },
  { key: 'employees.create', methods: ['POST'], urlPatterns: [/^\/api\/employees\/?$/] },
  { key: 'employees.update', methods: ['PUT','PATCH'], urlPatterns: [/^\/api\/employees\/(?!upload-employees).+/] },
  { key: 'employees.delete', methods: ['DELETE'], urlPatterns: [/^\/api\/employees\/(?!upload-employees).+/] },
  { key: 'employees.resign', methods: ['PUT'], urlPatterns: [/^\/api\/employees\/.+\/resign$/] },
  { key: 'employees.undoResign', methods: ['PUT'], urlPatterns: [/^\/api\/employees\/.+\/undo-resign$/] },
  { key: 'employees.bulkUpload', methods: ['POST'], urlPatterns: [/^\/api\/employees\/upload-employees$/] },
  { key: 'employeeDocs.create', methods: ['POST'], urlPatterns: [/^\/api\/employee-docs\/?$/] },
  { key: 'employeeDocs.delete', methods: ['DELETE'], urlPatterns: [/^\/api\/employee-docs\/.+/] },
  { key: 'employeeSalaries.create', methods: ['POST'], urlPatterns: [/^\/api\/employee-salaries\/?$/] },
  { key: 'employeeSalaries.update', methods: ['PUT','PATCH'], urlPatterns: [/^\/api\/employee-salaries\/.+/] },
  { key: 'employeeSalaries.delete', methods: ['DELETE'], urlPatterns: [/^\/api\/employee-salaries\/.+/] },
  { key: 'trainings.create', methods: ['POST'], urlPatterns: [/^\/api\/trainings\/?$/] },
  { key: 'trainings.update', methods: ['PUT','PATCH'], urlPatterns: [/^\/api\/trainings\/.+/] },
  { key: 'trainings.delete', methods: ['DELETE'], urlPatterns: [/^\/api\/trainings\/.+/] },
  { key: 'localHolidays.create', methods: ['POST'], urlPatterns: [/^\/api\/local-holidays\/?$/] },
  { key: 'localHolidays.update', methods: ['PUT','PATCH'], urlPatterns: [/^\/api\/local-holidays\/.+/] },
  { key: 'localHolidays.delete', methods: ['DELETE'], urlPatterns: [/^\/api\/local-holidays\/.+/] },
  { key: 'suspensions.create', methods: ['POST'], urlPatterns: [/^\/api\/suspensions\/?$/] },
  { key: 'suspensions.update', methods: ['PUT','PATCH'], urlPatterns: [/^\/api\/suspensions\/.+/] },
  { key: 'suspensions.delete', methods: ['DELETE'], urlPatterns: [/^\/api\/suspensions\/.+/] },
  { key: 'deductionTypes.create', methods: ['POST'], urlPatterns: [/^\/api\/deduction-types\/?$/] },
  { key: 'deductionTypes.update', methods: ['PUT','PATCH'], urlPatterns: [/^\/api\/deduction-types\/.+/] },
  { key: 'deductionTypes.delete', methods: ['DELETE'], urlPatterns: [/^\/api\/deduction-types\/.+/] },
  { key: 'payslipRequests.create', methods: ['POST'], urlPatterns: [/^\/api\/payslip-requests\/?$/] },
  { key: 'payslipRequests.update', methods: ['PUT','PATCH'], urlPatterns: [/^\/api\/payslip-requests\/.+/] },
  { key: 'payslipRequests.delete', methods: ['DELETE'], urlPatterns: [/^\/api\/payslip-requests\/.+/] },
  { key: 'dtrRequests.create', methods: ['POST'], urlPatterns: [/^\/api\/dtr-requests\/?$/] },
  { key: 'dtrRequests.update', methods: ['PUT','PATCH'], urlPatterns: [/^\/api\/dtr-requests\/.+/] },
  { key: 'dtrRequests.delete', methods: ['DELETE'], urlPatterns: [/^\/api\/dtr-requests\/.+/] },
  { key: 'dtr.generate', methods: ['POST'], urlPatterns: [/^\/api\/dtr\/upload$/,/^\/api\/dtr\/log-generation$/] },
  { key: 'features.suggest', methods: ['POST'], urlPatterns: [/^\/api\/features\/suggest$/] },
  { key: 'payslipRequests.sendEmail', methods: ['POST'], urlPatterns: [/^\/api\/payslip-requests\/.+\/send-email$/] },
  { key: 'notifications.sendNoTimeRecord', methods: ['POST'], urlPatterns: [/^\/api\/notifications\/no-time-record$/] },
  { key: 'notifications.sendNoTimeRecordBulk', methods: ['POST'], urlPatterns: [/^\/api\/notifications\/no-time-record\/bulk$/] },
  { key: 'notifications.create', methods: ['POST'], urlPatterns: [/^\/api\/notifications\/?$/] },
  { key: 'notifications.update', methods: ['PUT','PATCH'], urlPatterns: [/^\/api\/notifications\/.+/] },
  { key: 'notifications.delete', methods: ['DELETE'], urlPatterns: [/^\/api\/notifications\/.+/] },
  { key: 'dtrLogs.markRead', methods: ['PUT'], urlPatterns: [/^\/api\/dtr-logs\/.+\/read$/] },
  { key: 'dtrLogs.markAllRead', methods: ['PUT'], urlPatterns: [/^\/api\/dtr-logs\/read-all$/] },
  { key: 'dtrGenerationLogs.markRead', methods: ['PUT'], urlPatterns: [/^\/api\/dtr-generation-logs\/.+\/read$/] },
  { key: 'dtrGenerationLogs.markAllRead', methods: ['PUT'], urlPatterns: [/^\/api\/dtr-generation-logs\/read-all$/] },
  { key: 'dtrRequests.markRead', methods: ['PUT'], urlPatterns: [/^\/api\/dtr-requests\/.+\/read$/] },
  { key: 'dtrRequests.markAllRead', methods: ['PUT'], urlPatterns: [/^\/api\/dtr-requests\/read-all$/] },
  { key: 'payslipRequests.markRead', methods: ['PUT'], urlPatterns: [/^\/api\/payslip-requests\/.+\/read$/] },
  { key: 'payslipRequests.markAllRead', methods: ['PUT'], urlPatterns: [/^\/api\/payslip-requests\/read-all$/] },
];

export default demoActions;
